version: '3.3'
services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-books_database}
  library:
    build: ./library
    ports:
      - 3000:3000
    env_file: 
      - .env
    depends_on:
      - mongodb
    command: npm start
    volumes:
      - ./library:/008-nestjs-db/library