version: "3.3"
services: 
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-todos_database}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb
  counter:
    build: ./counter
    ports: 
      - 3001:3001
    environment:
      - PORT=3001
    command: npm start
    volumes: 
      - ./counter:/011-mongo/counter
  library:
    build: ./library
    ports: 
      - 3000:3000
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-todos_database}
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb
    command: npm start
    volumes: 
      - ./library/public/book:/011-mongo/library/public/book
      - ./library/public/cover:/011-mongo/library/public/cover